// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        // Desktop Firebase apps not registered — reuse Android options
        // (same project as tool/seed_firestore.dart).
        return android;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc9_fO6WgrQh7YLY00ZaZDjgW1EeYHthY',
    appId: '1:201515597019:android:ccadce210455313375e0fe',
    messagingSenderId: '201515597019',
    projectId: 'rafiq-academy',
    storageBucket: 'rafiq-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAf6iluHn9dne9ozWAMva_x7mSQwU7Om4',
    appId: '1:201515597019:ios:12f98908cfa6519875e0fe',
    messagingSenderId: '201515597019',
    projectId: 'rafiq-academy',
    storageBucket: 'rafiq-academy.firebasestorage.app',
    iosBundleId: 'com.example.rafiqAcademy',
  );
}
